import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import BottomSheet from "../src/Components/BottomSheet/BottomSheet";
import GInput from "../src/Components/GInput/GInput";
import "../styles/routes/Place.scss";

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  const router = useRouter();
  const place = router.query.place;
  const [localData, setLocalData] = useState({
    name: "",
    email: "",
    majorAndYear: "1",
    answer: "",
    location: place,
  });
  const setData = (data) => {
    localStorage.setItem("data", JSON.stringify(data));
  };
  const post = "https://www.instagram.com/p/Celi7BaBIeH/";

  useEffect(() => {
    if (localStorage.getItem("data")) {
      setLocalData({
        location: place,
        ...JSON.parse(localStorage.getItem("data")),
      });
    }
  }, [isOpen]);
  return (
    <div className="PlaceWrapper">
      <Head>
        <title>GDSC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/gdscLogo.png" />
      </Head>
      {isOpen ? (
        <BottomSheet setData={setData} setIsOpen={setIsOpen} />
      ) : (
        <>
          <div className="PlaceWrapper__top">
            <img
              className="PlaceWrapper__top--logo"
              src="/assets/gdscLogo.png"
            />
            <img
              className="PlaceWrapper__top--squareStretch"
              src="/assets/squareStretch.svg"
            />
          </div>
          <div className="PlaceWrapper__heading">
            <h2>Hello, {localData.name}</h2>
            <p>
              Lorem ipsum dolor sit amet consectetur dolor sit adipiscing elit
              Ut et.
            </p>
          </div>

          <div className="PlaceWrapper__funfact">
            <h3>
              Welcome to <span>{place}</span>
            </h3>
            <div className="PlaceWrapper__funfact--card">
              <img
                className="PlaceWrapper__funfact--placeImg"
                src="/assets/DiningGif.png"
              />
              <p>
                The dining hall with the most number of attractions for a foodie
                with evening snacks to midnight snacks.
              </p>
              <img
                className="PlaceWrapper__funfact--noise"
                src="/assets/Noise.svg"
              />
            </div>
          </div>

          <form
            className="PlaceWrapper__question"
            onSubmit={(e) => {
              e.preventDefault();
              setData(localData);

              fetch("/api/excel", {
                method: "POST",
                headers: {
                  "Content-Type": "application/json",
                },
                body: JSON.stringify(localData),
              })
                .then((r) => r.text())
                .then((result) => {
                  if (window.confirm("Thanks for answering the question!")) {
                    window.location.href = post;
                  }
                })
                .catch(() => {
                  window.alert("Some error occured. Please try again.");
                });
            }}
          >
            <h2>Lorem ipsum dolor sit amet consectetur.</h2>
            <p>
              Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa
              mi. Aliquam in hendrerit urna. Pellentesque sit?
            </p>
            <GInput
              id="answer"
              label="Write your answer..."
              setValue={(e) => {
                setLocalData({ ...localData, answer: e.target.value });
              }}
            />
            <div className="PlaceWrapper__question--buttonContainer">
              <img src="/assets/yetiThumb.svg" />
              <button type="submit">Submit</button>
            </div>
          </form>
          <footer className="PlaceWrapper__footer">
            <span>
              <img src="/assets/gdscLogo.png" />
              <p>Google Developer Student Clubs</p>
            </span>
            <p>Shiv Nadar University</p>
          </footer>
        </>
      )}
    </div>
  );
}
